// Components
import { Navbar } from "../../components/Layout/Navbar";

// Font
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

// Styles
import "../globals.css";

// Metadata
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="min-h-screen py-6 mx-auto max-w-7xl">{children}</main>
      </body>
    </html>
  );
}
